### ISSUE TITLE
[Question] Connection Closed

### ISSUE THREAD

**Issue by wandersonwhcr** [RafaelGSS/fastify-amqp#10]
Hello!

I have a simple problem: for some reason, like inactivity, the connection between amqplib and rabbitmq closes sometimes.

Currently I am using k8s to run node with fastify. Thinking about the problem, I added this hook into my project:

```js
fastify.addHook('onReady', function () {
  this.amqpConn.on('close', () => {
    fastify.close();
  });
});
```

k8s will restart the service and connection between amqplib and rabbitmq will be "fixed".

So... Is that correct? Makes sense?

**Comment by RafaelGSS** [comment]
I'm not sure, but when `ReplicaSet` reset your pod all the connections are closed. So, in your case always that RabbitMQ lost connection with your application it closes (and reconnect when ReplicaSet creates a new pod).

This could create instability in your system. I would create a logic to reconnect on failure like [here](https://www.cloudamqp.com/blog/2015-05-19-part2-2-rabbitmq-for-beginners_example-and-sample-code-node-js.html#set-up-a-connection).

A PR to create a logic for reconnection in the plugin is welcome as well.
