### ISSUE TITLE
Please add ability to change protocol of connection

### ISSUE THREAD

**Issue by vdvpie22** [RafaelGSS/fastify-amqp#15]
Please add: 
`const protocol = opts.protocol || 'amqp'`
and modify:
`amqpClient.connect(`${protocol}://${user}:${pass}@${host}:${port}`, { timeout }, function (err, connection) {`

in index.js 
For example AmazonMQ required amqps

**Comment by RafaelGSS** [comment]
Hey!

I'm +1 on it. Feel free to send a PR.

**Comment by RafaelGSS** [comment]
Closed #16
